// <auto-generated />
using System;
using IdentityExample.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IdentityExample.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("IdentityExample.Persistence.AspNetClaims", b =>
                {
                    b.Property<string>("ClaimValue")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("ClaimValue");

                    b.ToTable("AspNetClaims", (string)null);

                    b.HasData(
                        new
                        {
                            ClaimValue = "identity.customer.view"
                        },
                        new
                        {
                            ClaimValue = "identity.customer.create"
                        },
                        new
                        {
                            ClaimValue = "identity.customer.edit"
                        },
                        new
                        {
                            ClaimValue = "identity.customer.delete"
                        },
                        new
                        {
                            ClaimValue = "identity.customer.export"
                        },
                        new
                        {
                            ClaimValue = "identity.customer.import"
                        },
                        new
                        {
                            ClaimValue = "identity.customer.approve"
                        },
                        new
                        {
                            ClaimValue = "identity.customer.reject"
                        },
                        new
                        {
                            ClaimValue = "identity.customer.download"
                        },
                        new
                        {
                            ClaimValue = "identity.customer.upload"
                        },
                        new
                        {
                            ClaimValue = "identity.customer.print"
                        },
                        new
                        {
                            ClaimValue = "identity.customer.email"
                        },
                        new
                        {
                            ClaimValue = "identity.customer.archive"
                        },
                        new
                        {
                            ClaimValue = "identity.customer.restore"
                        },
                        new
                        {
                            ClaimValue = "identity.order.view"
                        },
                        new
                        {
                            ClaimValue = "identity.order.create"
                        },
                        new
                        {
                            ClaimValue = "identity.order.edit"
                        },
                        new
                        {
                            ClaimValue = "identity.order.delete"
                        },
                        new
                        {
                            ClaimValue = "identity.order.export"
                        },
                        new
                        {
                            ClaimValue = "identity.order.import"
                        },
                        new
                        {
                            ClaimValue = "identity.order.approve"
                        },
                        new
                        {
                            ClaimValue = "identity.order.reject"
                        },
                        new
                        {
                            ClaimValue = "identity.order.download"
                        },
                        new
                        {
                            ClaimValue = "identity.order.upload"
                        },
                        new
                        {
                            ClaimValue = "identity.order.print"
                        },
                        new
                        {
                            ClaimValue = "identity.order.email"
                        },
                        new
                        {
                            ClaimValue = "identity.order.archive"
                        },
                        new
                        {
                            ClaimValue = "identity.order.restore"
                        },
                        new
                        {
                            ClaimValue = "identity.product.view"
                        },
                        new
                        {
                            ClaimValue = "identity.product.create"
                        },
                        new
                        {
                            ClaimValue = "identity.product.edit"
                        },
                        new
                        {
                            ClaimValue = "identity.product.delete"
                        },
                        new
                        {
                            ClaimValue = "identity.product.export"
                        },
                        new
                        {
                            ClaimValue = "identity.product.import"
                        },
                        new
                        {
                            ClaimValue = "identity.product.approve"
                        },
                        new
                        {
                            ClaimValue = "identity.product.reject"
                        },
                        new
                        {
                            ClaimValue = "identity.product.download"
                        },
                        new
                        {
                            ClaimValue = "identity.product.upload"
                        },
                        new
                        {
                            ClaimValue = "identity.product.print"
                        },
                        new
                        {
                            ClaimValue = "identity.product.email"
                        },
                        new
                        {
                            ClaimValue = "identity.product.archive"
                        },
                        new
                        {
                            ClaimValue = "identity.product.restore"
                        },
                        new
                        {
                            ClaimValue = "identity.user.view"
                        },
                        new
                        {
                            ClaimValue = "identity.user.create"
                        },
                        new
                        {
                            ClaimValue = "identity.user.edit"
                        },
                        new
                        {
                            ClaimValue = "identity.user.delete"
                        },
                        new
                        {
                            ClaimValue = "identity.user.export"
                        },
                        new
                        {
                            ClaimValue = "identity.user.import"
                        },
                        new
                        {
                            ClaimValue = "identity.user.approve"
                        },
                        new
                        {
                            ClaimValue = "identity.user.reject"
                        },
                        new
                        {
                            ClaimValue = "identity.user.download"
                        },
                        new
                        {
                            ClaimValue = "identity.user.upload"
                        },
                        new
                        {
                            ClaimValue = "identity.user.print"
                        },
                        new
                        {
                            ClaimValue = "identity.user.email"
                        },
                        new
                        {
                            ClaimValue = "identity.user.archive"
                        },
                        new
                        {
                            ClaimValue = "identity.user.restore"
                        },
                        new
                        {
                            ClaimValue = "identity.report.view"
                        },
                        new
                        {
                            ClaimValue = "identity.report.create"
                        },
                        new
                        {
                            ClaimValue = "identity.report.edit"
                        },
                        new
                        {
                            ClaimValue = "identity.report.delete"
                        },
                        new
                        {
                            ClaimValue = "identity.report.export"
                        },
                        new
                        {
                            ClaimValue = "identity.report.import"
                        },
                        new
                        {
                            ClaimValue = "identity.report.approve"
                        },
                        new
                        {
                            ClaimValue = "identity.report.reject"
                        },
                        new
                        {
                            ClaimValue = "identity.report.download"
                        },
                        new
                        {
                            ClaimValue = "identity.report.upload"
                        },
                        new
                        {
                            ClaimValue = "identity.report.print"
                        },
                        new
                        {
                            ClaimValue = "identity.report.email"
                        },
                        new
                        {
                            ClaimValue = "identity.report.archive"
                        },
                        new
                        {
                            ClaimValue = "identity.report.restore"
                        },
                        new
                        {
                            ClaimValue = "identity.admin.view"
                        },
                        new
                        {
                            ClaimValue = "identity.admin.create"
                        },
                        new
                        {
                            ClaimValue = "identity.admin.edit"
                        },
                        new
                        {
                            ClaimValue = "identity.admin.delete"
                        },
                        new
                        {
                            ClaimValue = "identity.admin.export"
                        },
                        new
                        {
                            ClaimValue = "identity.admin.import"
                        },
                        new
                        {
                            ClaimValue = "identity.admin.approve"
                        },
                        new
                        {
                            ClaimValue = "identity.admin.reject"
                        },
                        new
                        {
                            ClaimValue = "identity.admin.download"
                        },
                        new
                        {
                            ClaimValue = "identity.admin.upload"
                        },
                        new
                        {
                            ClaimValue = "identity.admin.print"
                        },
                        new
                        {
                            ClaimValue = "identity.admin.email"
                        },
                        new
                        {
                            ClaimValue = "identity.admin.archive"
                        },
                        new
                        {
                            ClaimValue = "identity.admin.restore"
                        },
                        new
                        {
                            ClaimValue = "identity.invoice.view"
                        },
                        new
                        {
                            ClaimValue = "identity.invoice.create"
                        },
                        new
                        {
                            ClaimValue = "identity.invoice.edit"
                        },
                        new
                        {
                            ClaimValue = "identity.invoice.delete"
                        },
                        new
                        {
                            ClaimValue = "identity.invoice.export"
                        },
                        new
                        {
                            ClaimValue = "identity.invoice.import"
                        },
                        new
                        {
                            ClaimValue = "identity.invoice.approve"
                        },
                        new
                        {
                            ClaimValue = "identity.invoice.reject"
                        },
                        new
                        {
                            ClaimValue = "identity.invoice.download"
                        },
                        new
                        {
                            ClaimValue = "identity.invoice.upload"
                        },
                        new
                        {
                            ClaimValue = "identity.invoice.print"
                        },
                        new
                        {
                            ClaimValue = "identity.invoice.email"
                        },
                        new
                        {
                            ClaimValue = "identity.invoice.archive"
                        },
                        new
                        {
                            ClaimValue = "identity.invoice.restore"
                        },
                        new
                        {
                            ClaimValue = "identity.payment.view"
                        },
                        new
                        {
                            ClaimValue = "identity.payment.create"
                        },
                        new
                        {
                            ClaimValue = "identity.payment.edit"
                        },
                        new
                        {
                            ClaimValue = "identity.payment.delete"
                        },
                        new
                        {
                            ClaimValue = "identity.payment.export"
                        },
                        new
                        {
                            ClaimValue = "identity.payment.import"
                        },
                        new
                        {
                            ClaimValue = "identity.payment.approve"
                        },
                        new
                        {
                            ClaimValue = "identity.payment.reject"
                        },
                        new
                        {
                            ClaimValue = "identity.payment.download"
                        },
                        new
                        {
                            ClaimValue = "identity.payment.upload"
                        },
                        new
                        {
                            ClaimValue = "identity.payment.print"
                        },
                        new
                        {
                            ClaimValue = "identity.payment.email"
                        },
                        new
                        {
                            ClaimValue = "identity.payment.archive"
                        },
                        new
                        {
                            ClaimValue = "identity.payment.restore"
                        },
                        new
                        {
                            ClaimValue = "identity.inventory.view"
                        },
                        new
                        {
                            ClaimValue = "identity.inventory.create"
                        },
                        new
                        {
                            ClaimValue = "identity.inventory.edit"
                        },
                        new
                        {
                            ClaimValue = "identity.inventory.delete"
                        },
                        new
                        {
                            ClaimValue = "identity.inventory.export"
                        },
                        new
                        {
                            ClaimValue = "identity.inventory.import"
                        },
                        new
                        {
                            ClaimValue = "identity.inventory.approve"
                        },
                        new
                        {
                            ClaimValue = "identity.inventory.reject"
                        },
                        new
                        {
                            ClaimValue = "identity.inventory.download"
                        },
                        new
                        {
                            ClaimValue = "identity.inventory.upload"
                        },
                        new
                        {
                            ClaimValue = "identity.inventory.print"
                        },
                        new
                        {
                            ClaimValue = "identity.inventory.email"
                        },
                        new
                        {
                            ClaimValue = "identity.inventory.archive"
                        },
                        new
                        {
                            ClaimValue = "identity.inventory.restore"
                        },
                        new
                        {
                            ClaimValue = "identity.analytics.view"
                        },
                        new
                        {
                            ClaimValue = "identity.analytics.create"
                        },
                        new
                        {
                            ClaimValue = "identity.analytics.edit"
                        },
                        new
                        {
                            ClaimValue = "identity.analytics.delete"
                        },
                        new
                        {
                            ClaimValue = "identity.analytics.export"
                        },
                        new
                        {
                            ClaimValue = "identity.analytics.import"
                        },
                        new
                        {
                            ClaimValue = "identity.analytics.approve"
                        },
                        new
                        {
                            ClaimValue = "identity.analytics.reject"
                        },
                        new
                        {
                            ClaimValue = "identity.analytics.download"
                        },
                        new
                        {
                            ClaimValue = "identity.analytics.upload"
                        },
                        new
                        {
                            ClaimValue = "identity.analytics.print"
                        },
                        new
                        {
                            ClaimValue = "identity.analytics.email"
                        },
                        new
                        {
                            ClaimValue = "identity.analytics.archive"
                        },
                        new
                        {
                            ClaimValue = "identity.analytics.restore"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
